server {
    listen 8080;
    server_name localhost;
    client_max_body_size 1000000;
    root ./www;
    host 127.0.0.1;
    index index.html;

    error_page 400 /errors/400_bad_request.html;
    error_page 403 /errors/403_forbidden.html;
    error_page 404 /errors/404_not_found.html;
    error_page 413 /errors/413_payload_too_large.html;
    error_page 500 /errors/500_internal_server_error.html;
    error_page 502 /errors/502_bad_gateway.html;
    error_page 504 /errors/504_gateway_timeout.html;

    location / {
        allowed_methods GET POST DELETE;
    }

    location /redirect {
        return /explode/;
    }

}